#!/usr/bin/env bash
# =============================================================================
# RiceGuard CCTV Relay - Automated MediaMTX setup on Jetson Nano
# -----------------------------------------------------------------------------
# Topology:
#   [Imou CCTV] --eth--> [Jetson eth0] -- MediaMTX --> {wg0 (VPN), usb1 (LAN), lo}
#
# Subcommands:
#   discover    Sniff eth0 to learn camera IP + subnet, prompt for password,
#               verify with ffprobe, save to /etc/riceguard-cctv.env
#   install     Full setup (runs discover first if no env file present)
#   test        Verify camera + relay endpoints
#   status      Show service health and listen endpoints
#   snapshot    Capture one JPEG via the relay
#   uninstall   Remove everything (service, config, eth0 unit, env file)
# =============================================================================
set -euo pipefail

# --- Defaults (overridden by /etc/riceguard-cctv.env after discovery) --------
CCTV_ENV_FILE="/etc/riceguard-cctv.env"

CAMERA_IP=""
CAMERA_USER="admin"
CAMERA_PASS=""
CAMERA_STREAM_PATH="/cam/realmonitor?channel=1&subtype=0"
CAMERA_MAC=""

ETH_IFACE="eth0"
ETH_STATIC_IP=""
ETH_STATIC_CIDR="24"

RELAY_PATH_NAME="cam1"
RELAY_RTSP_PORT="8554"
RELAY_HLS_PORT="8888"
RELAY_WEBRTC_PORT="8889"
RELAY_READ_USER="viewer"
RELAY_READ_PASS="riceguard2026"

MEDIAMTX_VERSION="v1.9.3"
MEDIAMTX_ARCH="linux_arm64v8"
MEDIAMTX_DIR="/opt/mediamtx"
MEDIAMTX_USER="mediamtx"

WG_IFACE="wg0"
WIFI_IFACE="usb1"

TCPDUMP_DURATION=20   # seconds to listen for camera traffic during discovery
# -----------------------------------------------------------------------------

# Load saved discovery results if present
if [[ -f "$CCTV_ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CCTV_ENV_FILE"
fi

# Colors
R='\033[0;31m'; G='\033[0;32m'; Y='\033[1;33m'; B='\033[0;34m'; C='\033[0;36m'; N='\033[0m'
info()  { printf "${B}[*]${N} %s\n" "$*"; }
ok()    { printf "${G}[+]${N} %s\n" "$*"; }
warn()  { printf "${Y}[!]${N} %s\n" "$*"; }
fail()  { printf "${R}[x]${N} %s\n" "$*" >&2; }
step()  { printf "\n${C}=== %s ===${N}\n" "$*"; }

# --- Helpers -----------------------------------------------------------------
need_sudo() {
  if [[ $EUID -ne 0 ]]; then
    fail "This subcommand needs sudo. Try: sudo $0 $1"
    exit 1
  fi
}

iface_ip() {
  ip -4 -o addr show "$1" 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | head -n1
}

build_rtsp_url() {
  local user="$1" pass="$2" host="$3" port="$4" path="$5"
  if [[ -n "$user" && -n "$pass" ]]; then
    echo "rtsp://${user}:${pass}@${host}:${port}${path}"
  else
    echo "rtsp://${host}:${port}${path}"
  fi
}

wait_for_port() {
  local host="$1" port="$2" timeout="${3:-15}"
  local i=0
  while (( i < timeout )); do
    if (echo >/dev/tcp/"$host"/"$port") 2>/dev/null; then return 0; fi
    sleep 1; ((i++))
  done
  return 1
}

ensure_tools() {
  local missing=()
  for bin in "$@"; do
    command -v "$bin" >/dev/null 2>&1 || missing+=("$bin")
  done
  if (( ${#missing[@]} > 0 )); then
    warn "Installing missing tools: ${missing[*]}"
    apt-get update -qq
    apt-get install -y "${missing[@]}"
  fi
}

save_env_file() {
  umask 077
  cat > "$CCTV_ENV_FILE" <<EOF
# RiceGuard CCTV - generated by riceguard-cctv-relay.sh on $(date)
# DO NOT share this file — it contains camera credentials.
CAMERA_IP="$CAMERA_IP"
CAMERA_USER="$CAMERA_USER"
CAMERA_PASS="$CAMERA_PASS"
CAMERA_STREAM_PATH="$CAMERA_STREAM_PATH"
CAMERA_MAC="$CAMERA_MAC"
ETH_STATIC_IP="$ETH_STATIC_IP"
ETH_STATIC_CIDR="$ETH_STATIC_CIDR"
EOF
  chmod 600 "$CCTV_ENV_FILE"
  ok "Saved discovery results to $CCTV_ENV_FILE"
}

# --- discover ----------------------------------------------------------------
cmd_discover() {
  need_sudo discover
  step "Pre-flight"
  ensure_tools tcpdump arp-scan ffmpeg curl

  # Bring eth0 up without an IP so we can sniff what the camera wants
  ip link set "$ETH_IFACE" up
  ok "${ETH_IFACE} brought up (no IP yet)"

  step "Waiting for Ethernet link on ${ETH_IFACE}"
  local i=0
  while (( i < 30 )); do
    if [[ "$(cat /sys/class/net/${ETH_IFACE}/carrier 2>/dev/null || echo 0)" == "1" ]]; then
      ok "Link detected"
      break
    fi
    sleep 1; ((i++))
  done
  if [[ "$(cat /sys/class/net/${ETH_IFACE}/carrier 2>/dev/null || echo 0)" != "1" ]]; then
    fail "No link on ${ETH_IFACE} after 30s. Check cable + camera power."
    exit 1
  fi

  step "Listening for camera traffic (${TCPDUMP_DURATION}s) — ARP + DHCP on ${ETH_IFACE}"
  local pcap_text="/tmp/cctv-discover-$$.txt"
  timeout "$TCPDUMP_DURATION" tcpdump -i "$ETH_IFACE" -nn -e -l \
    'arp or port 67 or port 68' 2>/dev/null | tee "$pcap_text" || true

  if [[ ! -s "$pcap_text" ]]; then
    fail "Captured nothing. The camera may not be sending traffic — check power."
    rm -f "$pcap_text"; exit 1
  fi

  step "Parsing capture"

  # Case 1: ARP "who-has GATEWAY tell CAMERA" — best case, we get both IPs + MAC
  local arp_line
  arp_line=$(grep -E "who-has [0-9.]+ tell [0-9.]+" "$pcap_text" \
    | grep -vE "tell 0\.0\.0\.0" | head -1 || true)

  if [[ -n "$arp_line" ]]; then
    CAMERA_IP=$(echo "$arp_line" | grep -oE 'tell [0-9.]+' | awk '{print $2}')
    ETH_STATIC_IP=$(echo "$arp_line" | grep -oE 'who-has [0-9.]+' | awk '{print $2}')
    CAMERA_MAC=$(echo "$arp_line" | grep -oE '([0-9a-f]{2}:){5}[0-9a-f]{2}' | head -1)
    ok "Camera has static IP   : $CAMERA_IP"
    ok "Camera expects gateway : $ETH_STATIC_IP  (we'll take this address)"
    ok "Camera MAC             : $CAMERA_MAC"
  else
    # Case 2: gratuitous ARP "who-has X tell 0.0.0.0" — camera announcing its IP
    local gratuitous
    gratuitous=$(grep -E "who-has [0-9.]+ tell 0\.0\.0\.0" "$pcap_text" | head -1 || true)
    if [[ -n "$gratuitous" ]]; then
      CAMERA_IP=$(echo "$gratuitous" | grep -oE 'who-has [0-9.]+' | awk '{print $2}')
      ETH_STATIC_IP="${CAMERA_IP%.*}.1"   # assume gateway = .1 of same subnet
      CAMERA_MAC=$(echo "$gratuitous" | grep -oE '([0-9a-f]{2}:){5}[0-9a-f]{2}' | head -1)
      warn "Only saw gratuitous ARP. Assuming gateway = ${ETH_STATIC_IP}"
      ok "Camera IP  : $CAMERA_IP"
      ok "Camera MAC : $CAMERA_MAC"
    elif grep -q "BOOTP/DHCP" "$pcap_text"; then
      # Case 3: camera only does DHCP — we'd need to serve it
      fail "Camera is doing DHCP only — no static fallback detected."
      fail "Two options:"
      fail "  (a) Configure a static IP on the camera via Imou Life app, then re-run discover"
      fail "  (b) Install dnsmasq on this Jetson to serve DHCP on ${ETH_IFACE}"
      rm -f "$pcap_text"; exit 1
    else
      fail "Couldn't make sense of the capture. Raw output above."
      rm -f "$pcap_text"; exit 1
    fi
  fi
  rm -f "$pcap_text"

  step "Assigning ${ETH_STATIC_IP}/${ETH_STATIC_CIDR} to ${ETH_IFACE}"
  if ip -4 addr show "$ETH_IFACE" | grep -q "${ETH_STATIC_IP}/"; then
    ok "Already set"
  else
    ip addr add "${ETH_STATIC_IP}/${ETH_STATIC_CIDR}" dev "$ETH_IFACE"
    ok "Assigned"
  fi

  step "Verifying with ping + arp-scan"
  if ping -c 2 -W 2 "$CAMERA_IP" >/dev/null 2>&1; then
    ok "Camera responds to ping"
  else
    warn "Ping failed but ARP showed the camera; continuing"
  fi

  info "arp-scan view of ${ETH_IFACE}:"
  arp-scan --interface="$ETH_IFACE" --localnet || true

  # Confirm RTSP port is open
  if (echo >/dev/tcp/"$CAMERA_IP"/554) 2>/dev/null; then
    ok "RTSP port 554 is open on $CAMERA_IP"
  else
    warn "Port 554 closed. Enable RTSP in the Imou Life app:"
    warn "  Settings → Advanced Settings → enable RTSP / disable TLS encryption"
    warn "  Then re-run: sudo $0 discover"
    exit 1
  fi

  step "Authenticate"
  echo
  echo "The RTSP password is the camera's SAFETY CODE — NOT your Imou account password."
  echo "Find it on:"
  echo "  - The printed label/sticker on the camera body"
  echo "  - In Imou Life app: tap camera → settings → Device Label → under the QR code"
  echo

  local user_input
  read -r -p "  RTSP username [${CAMERA_USER}]: " user_input
  CAMERA_USER="${user_input:-$CAMERA_USER}"

  while true; do
    read -r -s -p "  RTSP password (input hidden): " CAMERA_PASS
    echo
    if [[ -z "$CAMERA_PASS" ]]; then
      warn "Empty password, try again."
      continue
    fi

    info "Verifying credentials against camera..."
    local test_url
    test_url=$(build_rtsp_url "$CAMERA_USER" "$CAMERA_PASS" "$CAMERA_IP" "554" "$CAMERA_STREAM_PATH")
    if ffprobe -v error -rtsp_transport tcp -stimeout 10000000 \
         -show_entries stream=codec_name,width,height,r_frame_rate \
         -of default=nw=1 "$test_url" 2>&1 | grep -qE '^codec_name='; then
      ok "Authentication successful — stream is decodable"
      ffprobe -v error -rtsp_transport tcp -stimeout 10000000 \
        -show_entries stream=codec_name,width,height,r_frame_rate \
        -of default=nw=1 "$test_url" 2>&1 | sed 's/^/    /'
      break
    else
      fail "Auth failed or stream not reachable."
      read -r -p "  Try a different password? [Y/n] " retry
      if [[ "${retry,,}" == "n" ]]; then
        rm -f "$CCTV_ENV_FILE" 2>/dev/null || true
        exit 1
      fi
    fi
  done

  save_env_file

  step "Discovery complete"
  echo "  Camera IP     : $CAMERA_IP"
  echo "  Camera MAC    : $CAMERA_MAC"
  echo "  Jetson eth0   : $ETH_STATIC_IP/$ETH_STATIC_CIDR"
  echo "  Saved to      : $CCTV_ENV_FILE"
  echo
  info "Next step: sudo $0 install"
}

# --- install -----------------------------------------------------------------
cmd_install() {
  need_sudo install

  # If we don't have camera details yet, run discover first
  if [[ -z "$CAMERA_IP" || -z "$CAMERA_PASS" || -z "$ETH_STATIC_IP" ]]; then
    warn "No saved discovery — running 'discover' first."
    cmd_discover
    # Reload env after discover writes it
    # shellcheck disable=SC1090
    source "$CCTV_ENV_FILE"
  else
    ok "Loaded saved discovery from $CCTV_ENV_FILE"
    echo "  Camera IP   : $CAMERA_IP"
    echo "  Camera MAC  : $CAMERA_MAC"
    echo "  Jetson eth0 : $ETH_STATIC_IP/$ETH_STATIC_CIDR"
  fi

  step "Pre-flight"
  ensure_tools curl tar ffmpeg

  if [[ "$(cat /sys/class/net/${ETH_IFACE}/carrier 2>/dev/null || echo 0)" != "1" ]]; then
    warn "${ETH_IFACE} has no link. Continuing anyway."
  else
    ok "${ETH_IFACE} link is up"
  fi

  step "Ensure ${ETH_STATIC_IP}/${ETH_STATIC_CIDR} on ${ETH_IFACE}"
  if ip -4 addr show "$ETH_IFACE" | grep -q "${ETH_STATIC_IP}/"; then
    ok "Already set"
  else
    ip addr add "${ETH_STATIC_IP}/${ETH_STATIC_CIDR}" dev "$ETH_IFACE" || true
    ip link set "$ETH_IFACE" up
    ok "Assigned"
  fi

  cat > /etc/systemd/system/riceguard-eth0.service <<EOF
[Unit]
Description=RiceGuard: assign static IP to ${ETH_IFACE} for CCTV segment
After=network-pre.target
Wants=network-pre.target
Before=mediamtx.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/sbin/ip link set ${ETH_IFACE} up
ExecStart=/bin/sh -c '/sbin/ip -4 addr show ${ETH_IFACE} | grep -q "${ETH_STATIC_IP}/" || /sbin/ip addr add ${ETH_STATIC_IP}/${ETH_STATIC_CIDR} dev ${ETH_IFACE}'
ExecStop=/sbin/ip addr del ${ETH_STATIC_IP}/${ETH_STATIC_CIDR} dev ${ETH_IFACE}

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable riceguard-eth0.service >/dev/null
  ok "riceguard-eth0.service installed"

  step "Installing MediaMTX ${MEDIAMTX_VERSION}"
  if ! id "$MEDIAMTX_USER" >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /usr/sbin/nologin "$MEDIAMTX_USER"
    ok "Created system user: $MEDIAMTX_USER"
  fi

  mkdir -p "$MEDIAMTX_DIR"
  cd "$MEDIAMTX_DIR"
  local tarball="mediamtx_${MEDIAMTX_VERSION}_${MEDIAMTX_ARCH}.tar.gz"
  local url="https://github.com/bluenviron/mediamtx/releases/download/${MEDIAMTX_VERSION}/${tarball}"

  if [[ ! -x "${MEDIAMTX_DIR}/mediamtx" ]]; then
    info "Downloading $url"
    curl -fsSL -o "$tarball" "$url"
    tar -xzf "$tarball"
    rm -f "$tarball"
    chmod +x mediamtx
    ok "MediaMTX binary installed"
  else
    ok "MediaMTX binary already present"
  fi

  step "Writing MediaMTX config"
  local camera_url
  camera_url=$(build_rtsp_url "$CAMERA_USER" "$CAMERA_PASS" "$CAMERA_IP" "554" "$CAMERA_STREAM_PATH")

  cat > "${MEDIAMTX_DIR}/mediamtx.yml" <<EOF
# RiceGuard CCTV relay
logLevel: info
logDestinations: [stdout]

rtspAddress: :${RELAY_RTSP_PORT}
rtmpDisable: yes
hlsAddress: :${RELAY_HLS_PORT}
hlsDisable: no
webrtcAddress: :${RELAY_WEBRTC_PORT}
webrtcDisable: no

authMethod: internal
authInternalUsers:
  - user: ${RELAY_READ_USER}
    pass: ${RELAY_READ_PASS}
    permissions:
      - action: read
      - action: playback
  - user: any
    pass:
    permissions:
      - action: api

paths:
  ${RELAY_PATH_NAME}:
    source: ${camera_url}
    sourceProtocol: tcp
    sourceOnDemand: no
    sourceOnDemandStartTimeout: 10s
    sourceOnDemandCloseAfter: 10s
EOF
  chown -R "$MEDIAMTX_USER":"$MEDIAMTX_USER" "$MEDIAMTX_DIR"
  chmod 640 "${MEDIAMTX_DIR}/mediamtx.yml"
  ok "Config at ${MEDIAMTX_DIR}/mediamtx.yml"

  step "Installing systemd service"
  cat > /etc/systemd/system/mediamtx.service <<EOF
[Unit]
Description=MediaMTX - RiceGuard CCTV RTSP relay
After=network-online.target riceguard-eth0.service
Wants=network-online.target
Requires=riceguard-eth0.service

[Service]
Type=simple
User=${MEDIAMTX_USER}
ExecStart=${MEDIAMTX_DIR}/mediamtx ${MEDIAMTX_DIR}/mediamtx.yml
Restart=always
RestartSec=5
LimitNOFILE=65536
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
ReadWritePaths=${MEDIAMTX_DIR}

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable mediamtx.service >/dev/null
  systemctl restart mediamtx.service
  ok "mediamtx.service enabled and started"

  step "Install complete"
  cmd_status
}

# --- status ------------------------------------------------------------------
cmd_status() {
  step "Saved config ($CCTV_ENV_FILE)"
  if [[ -f "$CCTV_ENV_FILE" ]]; then
    printf "  %-13s %s\n" "Camera IP:"   "${CAMERA_IP:-<unset>}"
    printf "  %-13s %s\n" "Camera MAC:"  "${CAMERA_MAC:-<unset>}"
    printf "  %-13s %s\n" "Jetson eth0:" "${ETH_STATIC_IP:-<unset>}/${ETH_STATIC_CIDR}"
  else
    warn "Not yet — run 'sudo $0 discover'"
  fi

  step "Service status"
  systemctl is-active riceguard-eth0.service >/dev/null 2>&1 \
    && ok "riceguard-eth0.service: active" \
    || warn "riceguard-eth0.service: inactive"

  systemctl is-active mediamtx.service >/dev/null 2>&1 \
    && ok "mediamtx.service: active" \
    || { warn "mediamtx.service: inactive"; systemctl --no-pager status mediamtx.service 2>/dev/null | head -10 || true; }

  step "Network endpoints"
  local lo_ip="127.0.0.1"
  local wg_ip wifi_ip eth_ip
  wg_ip=$(iface_ip "$WG_IFACE")
  wifi_ip=$(iface_ip "$WIFI_IFACE")
  eth_ip=$(iface_ip "$ETH_IFACE")
  printf "  %-10s %s\n" "$ETH_IFACE:"  "${eth_ip:-<no IP>}  (to camera)"
  printf "  %-10s %s\n" "$WIFI_IFACE:" "${wifi_ip:-<no IP>}  (LAN/WiFi)"
  printf "  %-10s %s\n" "$WG_IFACE:"   "${wg_ip:-<no IP>}  (VPN)"

  if systemctl is-active mediamtx.service >/dev/null 2>&1; then
    step "Relay URLs"
    local creds="${RELAY_READ_USER}:${RELAY_READ_PASS}"
    printf "  Localhost RTSP : rtsp://%s@%s:%s/%s\n" "$creds" "$lo_ip" "$RELAY_RTSP_PORT" "$RELAY_PATH_NAME"
    [[ -n "$wifi_ip" ]] && printf "  LAN RTSP       : rtsp://%s@%s:%s/%s\n" "$creds" "$wifi_ip" "$RELAY_RTSP_PORT" "$RELAY_PATH_NAME"
    [[ -n "$wg_ip" ]]   && printf "  VPN RTSP       : rtsp://%s@%s:%s/%s\n" "$creds" "$wg_ip"   "$RELAY_RTSP_PORT" "$RELAY_PATH_NAME"
    [[ -n "$wg_ip" ]]   && printf "  VPN HLS (web)  : http://%s:%s/%s/index.m3u8\n" "$wg_ip" "$RELAY_HLS_PORT" "$RELAY_PATH_NAME"
  fi
}

# --- test --------------------------------------------------------------------
cmd_test() {
  if [[ -z "$CAMERA_IP" ]]; then
    fail "No camera config. Run: sudo $0 discover"
    exit 1
  fi

  step "Test 1/5: Ping camera ($CAMERA_IP)"
  if ping -c 2 -W 2 "$CAMERA_IP" >/dev/null 2>&1; then
    ok "Camera responds to ping"
  else
    fail "Camera not reachable. Check link, eth0 IP, and camera power."
    return 1
  fi

  step "Test 2/5: Direct RTSP probe to camera"
  local direct_url
  direct_url=$(build_rtsp_url "$CAMERA_USER" "$CAMERA_PASS" "$CAMERA_IP" "554" "$CAMERA_STREAM_PATH")
  # ffmpeg 3.x: -timeout means listen mode. Use -stimeout (socket timeout, microseconds).
  if ffprobe -v error -rtsp_transport tcp -stimeout 10000000 \
        -show_entries stream=codec_name,width,height,r_frame_rate \
        -of default=nw=1 "$direct_url" 2>&1 | head -10; then
    ok "Direct RTSP from camera: OK"
  else
    fail "Direct RTSP failed. Re-run discover to refresh credentials."
    return 1
  fi

  step "Test 3/5: MediaMTX listening on :${RELAY_RTSP_PORT}"
  if wait_for_port 127.0.0.1 "$RELAY_RTSP_PORT" 20; then
    ok "MediaMTX listening on 127.0.0.1:${RELAY_RTSP_PORT}"
  else
    fail "MediaMTX not listening. Logs:"
    journalctl -u mediamtx.service --no-pager -n 30 || true
    return 1
  fi

  step "Test 4/5: Relay RTSP probe (each interface)"
  local lo_ip="127.0.0.1"
  local wg_ip wifi_ip
  wg_ip=$(iface_ip "$WG_IFACE")
  wifi_ip=$(iface_ip "$WIFI_IFACE")

  for host in "$lo_ip" "$wifi_ip" "$wg_ip"; do
    [[ -z "$host" ]] && continue
    local url
    url=$(build_rtsp_url "$RELAY_READ_USER" "$RELAY_READ_PASS" "$host" "$RELAY_RTSP_PORT" "/${RELAY_PATH_NAME}")
    info "Probing $host ..."
    if ffprobe -v error -rtsp_transport tcp -stimeout 10000000 \
          -show_entries stream=codec_name,width,height \
          -of default=nw=1 "$url" >/dev/null 2>&1; then
      ok "Relay reachable via $host"
    else
      warn "Relay probe failed via $host (may need a moment after first start)"
    fi
  done

  step "Test 5/5: Snapshot through relay"
  local snap="/tmp/riceguard-relay-snapshot.jpg"
  rm -f "$snap"
  local relay_url
  relay_url=$(build_rtsp_url "$RELAY_READ_USER" "$RELAY_READ_PASS" "127.0.0.1" "$RELAY_RTSP_PORT" "/${RELAY_PATH_NAME}")
  if ffmpeg -hide_banner -loglevel error -rtsp_transport tcp \
       -i "$relay_url" -frames:v 1 -q:v 2 "$snap"; then
    ok "Snapshot captured: $snap ($(du -h "$snap" | cut -f1))"
  else
    fail "Snapshot via relay failed"
    return 1
  fi

  step "All tests passed"
  cmd_status
}

# --- snapshot ----------------------------------------------------------------
cmd_snapshot() {
  local out="${1:-./cctv-snapshot-$(date +%Y%m%d-%H%M%S).jpg}"
  local relay_url
  relay_url=$(build_rtsp_url "$RELAY_READ_USER" "$RELAY_READ_PASS" "127.0.0.1" "$RELAY_RTSP_PORT" "/${RELAY_PATH_NAME}")
  info "Capturing from $relay_url -> $out"
  ffmpeg -hide_banner -loglevel error -rtsp_transport tcp \
    -i "$relay_url" -frames:v 1 -q:v 2 "$out"
  ok "Saved $out"
}

# --- uninstall ---------------------------------------------------------------
cmd_uninstall() {
  need_sudo uninstall
  step "Stopping and disabling services"
  systemctl disable --now mediamtx.service 2>/dev/null || true
  systemctl disable --now riceguard-eth0.service 2>/dev/null || true

  step "Removing files"
  rm -f /etc/systemd/system/mediamtx.service /etc/systemd/system/riceguard-eth0.service
  systemctl daemon-reload
  rm -rf "$MEDIAMTX_DIR"
  id "$MEDIAMTX_USER" >/dev/null 2>&1 && userdel "$MEDIAMTX_USER" || true

  step "Removing saved discovery and eth0 IP"
  if [[ -n "$ETH_STATIC_IP" ]]; then
    ip addr del "${ETH_STATIC_IP}/${ETH_STATIC_CIDR}" dev "$ETH_IFACE" 2>/dev/null || true
  fi
  rm -f "$CCTV_ENV_FILE"

  ok "Uninstalled"
}

# --- main --------------------------------------------------------------------
case "${1:-}" in
  discover)  shift; cmd_discover  "$@" ;;
  install)   shift; cmd_install   "$@" ;;
  test)      shift; cmd_test      "$@" ;;
  status)    shift; cmd_status    "$@" ;;
  snapshot)  shift; cmd_snapshot  "$@" ;;
  uninstall) shift; cmd_uninstall "$@" ;;
  ""|-h|--help|help)
    cat <<EOF
RiceGuard CCTV Relay - automated MediaMTX setup with discovery

Usage:
  sudo $0 discover     Sniff eth0 to learn camera IP/subnet, prompt for password,
                       verify with ffprobe, save to $CCTV_ENV_FILE
  sudo $0 install      Full setup (auto-runs discover if no saved config)
       $0 test         Verify camera + relay end-to-end
       $0 status       Show service health, endpoints, and saved discovery
       $0 snapshot [path]   Save one JPEG via the relay
  sudo $0 uninstall    Remove everything (services, binary, saved config)

Workflow on a fresh Jetson:
  1. Plug camera into eth0, power it on
  2. sudo $0 discover    # learns camera IP, prompts for safety code
  3. sudo $0 install     # uses saved discovery
  4. $0 test
  5. $0 snapshot ~/preview.jpg

The discover step performs:
  - tcpdump on $ETH_IFACE for ${TCPDUMP_DURATION}s to learn the camera's IP/gateway
  - arp-scan to confirm the camera is reachable
  - prompts for username + safety code, verifies with ffprobe
  - saves everything to $CCTV_ENV_FILE (chmod 600, root only)

EOF
    ;;
  *)
    fail "Unknown command: $1"
    exec "$0" help
    ;;
esac
